apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-cluster1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/igboma/test-deployment'
    targetRevision: main
    path: deployment  # Path to the deployment directory in the repo
  destination:
    server: 'https://192.168.64.3:8443'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
